version: '3.8'
services:
  gateway:
    container_name: api-gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - ./gateway/.env
    depends_on:
      user-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
    volumes:
      - ./gateway:/app
    networks:
      - ecommerce-net
  
  user-service:
    container_name: ecommerce-user-service
    build: 
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    env_file:
      - ./services/user-service/.env
    depends_on:
      - mongo
    volumes:
      - ./services/user-service:/app
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://user-service:4001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: npm run dev
    networks:
      - ecommerce-net
      
  product-service:
    container_name: ecommerce-product-service
    build: 
      context: ./services/product-service
      dockerfile: Dockerfile
    ports:
      - '4002:4002'
    env_file:
      - ./services/product-service/.env
    depends_on:
      - mongo
    volumes:
      - ./services/product-service:/app
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://product-service:4002/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: npm run dev 
    networks:
      - ecommerce-net

  cart-service:
    container_name: ecommerce-cart-service
    build: 
      context: ./services/cart-service
      dockerfile: Dockerfile
    ports:
      - '4003:4003'
    env_file:
      - ./services/cart-service/.env
    depends_on:
      - mongo
    volumes:
      - ./services/cart-service:/app
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://cart-service:4003/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: npm run dev 
    networks:
      - ecommerce-net
  
  order-service:
    container_name: ecommerce-order-service
    build: 
      context: ./services/order-service
      dockerfile: Dockerfile
    ports:
      - '4004:4004'
    env_file:
      - ./services/order-service/.env
    depends_on:
      mongo:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./services/order-service:/app
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://order-service:4004/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: npm run dev 
    networks:
      - ecommerce-net
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce-net
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ecommerce-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    env_file:
      - .env
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: ${KAFKA_CLUSTER_ID} 
    depends_on:
      - zookeeper
    networks:
      - ecommerce-net

networks:
  ecommerce-net:

volumes:
  mongo_data:
